language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install awscli

jobs:
  include:
    - stage: build & push master
      if: tag =~ ^v(\d+.?)+.*$
      script:
      - mkdir ./${TRAVIS_TAG};
      - tar -czvf ${TRAVIS_TAG}/chart.tgz chart;
      #- aws s3 sync ./${TRAVIS_TAG} s3://${AWS_S3_BUCKET}/charts/${TRAVIS_TAG}
  
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: ${AWS_S3_BUCKET}
  skip_cleanup: true
  local_dir: ./${TRAVIS_TAG}
  on:
    condition: ${TRAVIS_BRANCH} =~ ^v(\d+.?)+.*$
    tags: true
