apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: {{ .Values.serviceName }}
  ports:
  - name: http-default
    port: 80
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  sessionAffinity: None
  type: ClusterIP
